<a href="https://colab.research.google.com/github/2303a51733/230351733_B11_PDS/blob/main/lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Perform basic arithmetic operations like addition and subtraction
on 2D NumPy arrays representing matrices

In [3]:
import numpy as np
A=np.array([[20,30,40],[40,50,60]])
B=np.array([[15,10,25],[20,25,35]])
print(A)
print(B)


[[20 30 40]
 [40 50 60]]
[[15 10 25]
 [20 25 35]]


In [4]:
addition=np.add(A,B)
print(addition)
subtraction=np.subtract(A,B)
print(subtraction)

[[35 40 65]
 [60 75 95]]
[[ 5 20 15]
 [20 25 25]]


Apply statistical operations like mean, median, std, min, and max
to analyze 2D array data.

In [5]:
import numpy as np
scores = np.random.randint(0, 101, (4, 4))
print("Test Scores (4x4):\n", scores)
row_mean = np.mean(scores, axis=1)
print("\nRow-wise Mean (per student):\n", row_mean)
col_mean = np.mean(scores, axis=0)
print("\nColumn-wise Mean (per subject):\n", col_mean)
std_dev = np.std(scores)
variance = np.var(scores)
print("\nStandard Deviation of all scores:", std_dev)
print("Variance of all scores:", variance)
max_value = np.max(scores)
min_value = np.min(scores)
max_index = np.unravel_index(np.argmax(scores), scores.shape)
min_index = np.unravel_index(np.argmin(scores), scores.shape)
print("\nMaximum Score:", max_value)
print("Minimum Score:", min_value)

Test Scores (4x4):
 [[41 21 11 58]
 [64 89  4 21]
 [96 74 26 43]
 [67  8 85 63]]

Row-wise Mean (per student):
 [32.75 44.5  59.75 55.75]

Column-wise Mean (per subject):
 [67.   48.   31.5  46.25]

Standard Deviation of all scores: 29.466546179523654
Variance of all scores: 868.27734375

Maximum Score: 96
Minimum Score: 4


Apply statistical operations like mean, median, std, min, and max
to analyze 2D array data

In [6]:
import numpy as np
image = np.random.randint(0, 256, (3, 3, 3))
print("Original Image:\n", image)
red   = image[:, :, 0]
green = image[:, :, 1]
blue  = image[:, :, 2]
print("\nRed Channel:\n", red)
print("\nGreen Channel:\n", green)
print("\nBlue Channel:\n", blue)
print("\nAverage Red:", np.mean(red))
print("Average Green:", np.mean(green))
print("Average Blue:", np.mean(blue))
bright = np.clip(np.add(image, 50), 0, 255)
print("\nBrightened Image:\n", bright)
dark = np.clip(np.subtract(image, 50), 0, 255)
print("\nDarkened Image:\n", dark)


Original Image:
 [[[  8 204  15]
  [ 73 227 198]
  [211 244   8]]

 [[155  53  66]
  [195 218  29]
  [195  87   0]]

 [[ 41  73 108]
  [139  11 244]
  [202  57  70]]]

Red Channel:
 [[  8  73 211]
 [155 195 195]
 [ 41 139 202]]

Green Channel:
 [[204 227 244]
 [ 53 218  87]
 [ 73  11  57]]

Blue Channel:
 [[ 15 198   8]
 [ 66  29   0]
 [108 244  70]]

Average Red: 135.44444444444446
Average Green: 130.44444444444446
Average Blue: 82.0

Brightened Image:
 [[[ 58 254  65]
  [123 255 248]
  [255 255  58]]

 [[205 103 116]
  [245 255  79]
  [245 137  50]]

 [[ 91 123 158]
  [189  61 255]
  [252 107 120]]]

Darkened Image:
 [[[  0 154   0]
  [ 23 177 148]
  [161 194   0]]

 [[105   3  16]
  [145 168   0]
  [145  37   0]]

 [[  0  23  58]
  [ 89   0 194]
  [152   7  20]]]
